SELECT
    PRD.PRD_ID AS product_id,
    PRD.PRD_DESCRIPTION AS product_description,
    MTR.MTR_ID AS material_id,
    MTR.MTR_DESCRIPTION AS material_description,
    MTB.MTB_PERCENTAGE AS percentage,
    MPR.MTR_PRICE AS material_price,
    ROUND((CAST(MTB.MTB_PERCENTAGE AS FLOAT) * MPR.MTR_PRICE), 2) AS contribution_to_product_price

FROM
    PRODUCT PRD
JOIN
    MATERIALBILL MTB ON PRD.PRD_ID = MTB.PRD_ID
JOIN
    MATERIAL MTR ON MTB.MTR_ID = MTR.MTR_ID
JOIN
    MATERIALPRICE MPR ON MTR.MTR_ID = MPR.MTR_ID
WHERE
	MPR.MPR_VALID_FROM <= '2023-12-19'
    AND MPR.MPR_VALID_UNTIL >= '2023-12-19';
