SELECT
    MB1.MTR_ID,
    M.MTR_DESCRIPTION
FROM
    MATERIALBILL MB1
JOIN
    MATERIALBILL MB2 ON MB1.MTR_ID = MB2.MTR_ID
JOIN
    MATERIAL M ON MB1.MTR_ID = M.MTR_ID
JOIN
    PRODUCT P1 ON MB1.PRD_ID = P1.PRD_ID
JOIN
    PRODUCT P2 ON MB2.PRD_ID = P2.PRD_ID
WHERE
    P1.PRD_DESCRIPTION IN ('P1', 'P2')
    AND P2.PRD_DESCRIPTION = P1.PRD_DESCRIPTION;
